export const text = (locale, ru, en) => locale === "en" ? en : ru;

export const navLabels = {
  en: { home: "Home", physics: "Physics", simulator: "Simulator", ai: "AI", chat: "Articles", friends: "Friends", teachers: "Teachers", about: "About" },
};

export const englishTopics = {
  newton: { title: "Newton's laws", summary: "Force, mass, and acceleration determine motion.", theory: "Newton's first law states that an object remains at rest or moves uniformly unless an external force changes its motion.\n\nThe second law connects force, mass, and acceleration. The third law says that interacting bodies exert equal and opposite forces on each other." },
  optics: { title: "Optics", summary: "Light reflects, refracts, and splits into a spectrum.", theory: "Refraction changes the direction of light when it passes from one medium into another. The refractive indices and angles are connected by Snell's law.\n\nWhen light enters a denser medium, it bends toward the normal; when it leaves, it bends away from the normal." },
  gravity: { title: "Gravity", summary: "All objects with mass attract one another.", theory: "Gravity keeps planets in orbit and holds us on Earth's surface. Near Earth, free-fall acceleration is approximately 9.8 m/s².\n\nIgnoring air resistance, objects of different masses fall with the same acceleration." },
  waves: { title: "Waves", summary: "Oscillations transfer energy through space.", theory: "Sound, light, and water waves are examples of wave motion. Wavelength is the distance between neighboring peaks, while frequency is the number of oscillations per second.\n\nMechanical waves require a medium; electromagnetic waves can travel through a vacuum." },
  electric: { title: "Electric field", summary: "Charges create electric fields and interact.", theory: "An electric field is a region where a charged particle experiences force. Field lines point from positive to negative charges.\n\nCoulomb's law shows that electrostatic force depends on the charges and decreases with the square of the distance." },
  pendulum: { title: "Pendulum", summary: "Its period depends on length and gravity.", theory: "For small oscillations, a pendulum's period depends on its length and gravitational acceleration, but not on the mass of the bob.\n\nKinetic and potential energy continuously transform into each other during motion." },
  heat: { title: "Heat transfer", summary: "Heat moves by conduction, convection, and radiation.", theory: "The amount of heat depends on mass, specific heat capacity, and temperature change.\n\nConduction transfers heat through contact, convection through fluid motion, and radiation through electromagnetic waves." },
  magnetism: { title: "Magnetism", summary: "Moving charges create magnetic fields.", theory: "Magnetic fields act on moving charged particles. Magnetic induction is measured in teslas.\n\nThe right-hand rule determines field direction around a current-carrying wire." },
  projectile: { title: "Projectile motion", summary: "Horizontal motion combines with free fall.", theory: "Imagine throwing a ball forward and upward. Immediately after release, its motion can be divided into two independent directions.\n\nHorizontally, the ball moves at constant velocity:\n\n**x = v₀ · cos(α) · t**\n\nVertically, it first rises while gravity gradually slows it down, and then it begins to fall:\n\n**y = v₀ · sin(α) · t − gt² / 2**\n\nThe horizontal and vertical motions combine, so the object follows a curved path called a **parabola**. A greater initial speed produces a longer flight. The launch angle controls the shape of the trajectory: a small angle gives a lower path, while a large angle gives a higher one.\n\nHere **v₀** is the initial speed, **α** is the launch angle above the horizontal, **t** is time, **g** is gravitational acceleration, **x** is horizontal distance, and **y** is height.\n\nChange the speed and angle in the simulation and observe the trajectory under constant Earth gravity. The flight ends when the object reaches the surface again: **y = 0**." },
  hooke: { title: "Hooke's law", summary: "Elastic force is proportional to deformation.", theory: "Think of the spring in a pen or a toy shock absorber. When it is stretched or compressed, it tends to return to its original position. For small deformations, the elastic force follows Hooke's law: **F = −kx**.\n\nThe greater the deformation **x**, the greater the force magnitude. The spring constant **k** describes how difficult the spring is to deform: a stiffer spring has a larger value. The minus sign means that the force points opposite to the displacement and returns the object toward equilibrium.\n\nChange the mass, spring constant, and initial deformation in the simulation. Observe how they affect the force, oscillation period, and motion." },
  momentum: { title: "Conservation of momentum", summary: "Total momentum is conserved in a closed system.", theory: "An object's momentum equals its mass multiplied by its velocity: **p = mv**. Momentum has direction, so velocity to the right can be treated as positive and velocity to the left as negative.\n\nDuring a collision, the objects exert forces on each other, but the total momentum of a closed system is conserved: **m₁v₁ + m₂v₂ = m₁v₁′ + m₂v₂′**. An elastic collision also conserves kinetic energy. In a perfectly inelastic collision, the objects move together after impact, while some kinetic energy becomes internal energy, heat, and deformation.\n\nChange the masses, velocities, and collision type. Compare the system's momentum and kinetic energy before and after impact." },
  ohm: { title: "Ohm's law", summary: "Current depends on voltage and resistance.", theory: "Electric current can be pictured as the directed motion of charges through a circuit. Voltage **U** drives the charges, while resistance **R** opposes their motion. Ohm's law connects these quantities: **I = U / R**.\n\nIf resistance stays constant, doubling the voltage doubles the current. If voltage stays constant, increasing resistance reduces the current. For example, a thin or long wire usually has greater resistance and allows less current to flow.\n\nChange the voltage and resistance in the simulation, observe the conventional-current direction, and check the calculated current. When the voltage is zero, no current flows." },
};

export function localizeTopics(topics, locale) {
  if (locale !== "en") return topics;
  return topics.map((topic) => ({ ...topic, ...englishTopics[topic.id] }));
}

